"""
Attendance logger web UI for the weekly call.

A small Flask app that:
  1. Renders a checkbox list of the Roster.
  2. On submit, increments each checked person's count in a new
     "Attendance Tracker" tab (auto-created on first use), and fills the
     existing "Total Attendance" + "No Shows" columns on the most recent
     Tracker row.
  3. Optionally posts a confirmation to the Telegram thread. If a Groq
     API key is configured, the confirmation message is generated by
     Llama 3.3 70B for a warmer, personalised tone; otherwise a clean
     templated string is used.

Designed to deploy as a Cloud Run *Service* on the same Docker image as
bot.py. Cloud Run runs `gunicorn attendance_app:app` instead of
`python bot.py`; everything else (image, secrets, service account) is
shared with the existing weekly-call Job.
"""

import os
import json
import traceback
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import gspread
import requests
from flask import Flask, request, render_template_string
from google.oauth2.service_account import Credentials

try:
    from groq import Groq
    HAS_GROQ = True
except ImportError:
    HAS_GROQ = False


BOT_TOKEN = os.environ.get("BOT_TOKEN")
CHAT_ID = os.environ.get("CHAT_ID")
THREAD_ID = os.environ.get("THREAD_ID")
GCP_CREDENTIALS_JSON = os.environ.get("GCP_CREDENTIALS")
ATTENDANCE_PASSCODE = os.environ.get("ATTENDANCE_PASSCODE", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
POST_TELEGRAM_CONFIRMATION = (
    os.environ.get("POST_TELEGRAM_CONFIRMATION", "true").strip().lower() == "true"
)

SHEET_NAME = "Weekly Call Tracker"
TRACKER_TAB = "Tracker"
ROSTER_TAB = "Roster"
ATTENDANCE_TAB = "Attendance Tracker"

COL_WEEK_OF = "Date of Call"
COL_SHLOK = "Shlok + Jaynaad"
COL_PRASANG = "Prasang"
COL_ENDING_SHLOK = "Ending Shlok"
COL_TOTAL_ATTENDANCE = "Total Attendance"
COL_NO_SHOWS = "No Shows"

TZ = ZoneInfo("America/New_York")
HARIBHAI_NAME = "Manav"

app = Flask(__name__)


def _col_letter(n: int) -> str:
    """1-based column index -> spreadsheet letters (1 -> A, 27 -> AA)."""
    s = ""
    while n:
        n, r = divmod(n - 1, 26)
        s = chr(65 + r) + s
    return s


def connect_to_sheet():
    if not GCP_CREDENTIALS_JSON:
        raise RuntimeError("GCP_CREDENTIALS env var is not set")
    scope = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive",
    ]
    creds = Credentials.from_service_account_info(
        json.loads(GCP_CREDENTIALS_JSON), scopes=scope
    )
    return gspread.authorize(creds).open(SHEET_NAME)


def read_roster(spreadsheet):
    ws = spreadsheet.worksheet(ROSTER_TAB)
    rows = ws.get_all_values()
    if len(rows) <= 1:
        return []
    out = []
    for row in rows[1:]:
        if not row or not row[0].strip():
            continue
        name = row[0].strip()
        tag = row[1].strip() if len(row) > 1 else ""
        status = row[2].strip().lower() if len(row) > 2 else ""
        out.append(
            {
                "name": name,
                "tag": tag or name,
                "on_vacation": status == "vacation",
            }
        )
    return out


def find_current_call_row(tracker_ws):
    """
    Locate the Tracker row for the most recently completed call.

    The bot writes a row each Monday with `Date of Call` set to the
    upcoming Tuesday. After that Tuesday's call we look up the row by
    that Tuesday's date. If the exact date isn't found (timing edge
    case), fall back to the last row in the sheet.
    """
    records = tracker_ws.get_all_records()
    if not records:
        return None, None
    now = datetime.now(TZ)
    days_since_tuesday = (now.weekday() - 1) % 7
    target_date = (now - timedelta(days=days_since_tuesday)).date()
    target_str = target_date.strftime("%b %d, %Y")
    for i, row in enumerate(records, start=2):
        if str(row.get(COL_WEEK_OF, "")).strip() == target_str:
            return i, row
    return len(records) + 1, records[-1]


def get_or_create_attendance_tab(spreadsheet):
    try:
        return spreadsheet.worksheet(ATTENDANCE_TAB)
    except gspread.WorksheetNotFound:
        ws = spreadsheet.add_worksheet(title=ATTENDANCE_TAB, rows=200, cols=4)
        ws.append_row(["Name", "Attended Count", "Last Attended"])
        return ws


def update_attendance_tab(spreadsheet, attended_names, call_date_str):
    ws = get_or_create_attendance_tab(spreadsheet)
    values = ws.get_all_values()
    name_to_row = {}
    for i, row in enumerate(values[1:], start=2):
        if row and row[0].strip():
            name_to_row[row[0].strip()] = (i, row)

    batch_updates = []
    new_rows = []
    for name in attended_names:
        if name in name_to_row:
            row_idx, row_vals = name_to_row[name]
            try:
                current = int(row_vals[1]) if len(row_vals) > 1 and row_vals[1] else 0
            except ValueError:
                current = 0
            batch_updates.append(
                {
                    "range": f"B{row_idx}:C{row_idx}",
                    "values": [[current + 1, call_date_str]],
                }
            )
        else:
            new_rows.append([name, 1, call_date_str])

    if batch_updates:
        ws.batch_update(batch_updates)
    if new_rows:
        ws.append_rows(new_rows)


def update_tracker_row(tracker_ws, row_idx, headers, attended_count, no_shows_str):
    try:
        total_col = headers.index(COL_TOTAL_ATTENDANCE) + 1
        no_show_col = headers.index(COL_NO_SHOWS) + 1
    except ValueError as e:
        raise RuntimeError(f"Missing column in Tracker tab: {e}")
    tracker_ws.batch_update(
        [
            {"range": f"{_col_letter(total_col)}{row_idx}", "values": [[attended_count]]},
            {"range": f"{_col_letter(no_show_col)}{row_idx}", "values": [[no_shows_str]]},
        ]
    )


def generate_telegram_summary(call_date, attended, no_shows, role_holders_map):
    """Return the Telegram confirmation text. Uses Groq when configured."""
    if HAS_GROQ and GROQ_API_KEY:
        try:
            client = Groq(api_key=GROQ_API_KEY)
            roles_text = ", ".join(
                f"{role}={name}" for role, name in role_holders_map.items() if name
            )
            prompt = (
                "Write a short Telegram confirmation message (3-5 lines max) "
                "recapping a BAPS Swaminarayan weekly preparation call's "
                "attendance. Warm and uplifting but factual. Use names "
                "directly. Plain text only, no markdown, simple newlines.\n\n"
                f"Call date: {call_date}\n"
                f"Attended ({len(attended)}): {', '.join(attended)}\n"
                f"Role-holders this week: {roles_text}\n"
                f"No-shows from role-holders ({len(no_shows)}): "
                f"{', '.join(no_shows) if no_shows else 'None - all role-holders attended'}\n\n"
                'End with "Jai Swaminarayan!"'
            )
            resp = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.6,
                max_tokens=220,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            print(f"Groq summary failed, using template: {e}", flush=True)

    lines = [f"Attendance logged for {call_date}", ""]
    lines.append(f"{len(attended)} attended: {', '.join(attended)}")
    if no_shows:
        plural = "s" if len(no_shows) != 1 else ""
        lines.append(
            f"{len(no_shows)} no-show{plural} from role-holders: {', '.join(no_shows)}"
        )
    else:
        lines.append("All role-holders attended.")
    return "\n".join(lines)


def post_to_telegram(text):
    if not (BOT_TOKEN and CHAT_ID):
        return
    payload = {"chat_id": int(CHAT_ID), "text": text}
    if THREAD_ID:
        payload["message_thread_id"] = int(THREAD_ID)
    try:
        requests.post(
            f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
            json=payload,
            timeout=20,
        )
    except Exception as e:
        print(f"Telegram post failed (non-fatal): {e}", flush=True)


INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Log Attendance</title>
  <style>
    *,*::before,*::after { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           max-width: 560px; margin: 0 auto; padding: 1.25rem 1rem 3rem;
           background: #f6f6f7; color: #1a1a1a; }
    h1 { font-size: 1.5rem; margin: 0 0 .15rem; }
    .subtle { color: #6a6a6a; font-size: .9rem; }
    .card { background: #fff; border-radius: 12px; padding: 1rem;
            margin: 1rem 0; box-shadow: 0 1px 3px rgba(0,0,0,.06); }
    dl.roles { display: grid; grid-template-columns: max-content 1fr;
               gap: .35rem .9rem; margin: 0; font-size: .92rem; }
    dl.roles dt { color: #6a6a6a; }
    dl.roles dd { margin: 0; font-weight: 500; }
    label.field { font-weight: 600; display: block; margin-bottom: .5rem; }
    input[type=password] {
      width: 100%; padding: .7rem .8rem; font-size: 1rem;
      border: 1px solid #ccc; border-radius: 8px;
      -webkit-appearance: none; }
    .row { display: flex; justify-content: space-between; align-items: center;
           margin-bottom: .6rem; }
    .actions { display: flex; gap: .5rem; margin-bottom: .25rem; }
    .actions button { flex: 1; background: #fff; color: #333;
                      border: 1px solid #ddd; padding: .5rem;
                      border-radius: 8px; font-weight: 500; cursor: pointer; }
    .roster-item { display: flex; align-items: center; padding: .55rem 0;
                   border-top: 1px solid #eee; }
    .roster-item:first-of-type { border-top: 0; }
    .roster-item input[type=checkbox] { width: 22px; height: 22px;
                                         margin-right: .8rem; accent-color: #ff6b00; }
    .roster-item label { flex: 1; font-size: 1rem; cursor: pointer; }
    .vacation { color: #999; font-size: .8rem; }
    button.primary { width: 100%; padding: .85rem; font-size: 1rem;
                     font-weight: 600; background: #ff6b00; color: #fff;
                     border: 0; border-radius: 10px; cursor: pointer;
                     margin-top: 1rem; }
    button.primary:active { background: #e25e00; }
  </style>
</head>
<body>
  <h1>Log Attendance</h1>
  <div class="subtle">Week of <strong>{{ call_date }}</strong></div>

  {% if role_holders %}
  <div class="card">
    <div style="font-weight:600;margin-bottom:.5rem;">This week's roles</div>
    <dl class="roles">
      {% for role, name in role_holders.items() %}
      <dt>{{ role }}</dt>
      <dd>{{ name or '\u2014' }}</dd>
      {% endfor %}
    </dl>
  </div>
  {% endif %}

  <form method="POST" action="/submit" autocomplete="on">
    <div class="card">
      <label class="field" for="passcode">Passcode</label>
      <input id="passcode" name="passcode" type="password"
             autocomplete="current-password" required>
    </div>

    <div class="card">
      <div class="row">
        <strong>Who attended?</strong>
        <span class="subtle" id="count">0 selected</span>
      </div>
      <div class="actions">
        <button type="button" onclick="toggleAll(true)">Select all</button>
        <button type="button" onclick="toggleAll(false)">Clear</button>
      </div>
      {% for person in roster %}
      <div class="roster-item">
        <input type="checkbox" id="p{{ loop.index }}"
               name="attended" value="{{ person.name }}">
        <label for="p{{ loop.index }}">
          {{ person.name }}{% if person.on_vacation %}<span class="vacation"> (vacation)</span>{% endif %}
        </label>
      </div>
      {% endfor %}
    </div>

    <button type="submit" class="primary">Log attendance</button>
  </form>

  <script>
    const cbs = document.querySelectorAll('input[name=attended]');
    const counter = document.getElementById('count');
    function updateCount() {
      const n = [...cbs].filter(c => c.checked).length;
      counter.textContent = n + ' selected';
    }
    cbs.forEach(c => c.addEventListener('change', updateCount));
    function toggleAll(state) {
      cbs.forEach(c => c.checked = state);
      updateCount();
    }
  </script>
</body>
</html>"""


SUCCESS_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Logged</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           max-width: 560px; margin: 0 auto; padding: 1.25rem 1rem 3rem;
           background: #f6f6f7; color: #1a1a1a; }
    h1 { font-size: 1.5rem; margin: 0 0 .75rem; }
    .card { background: #fff; border-radius: 12px; padding: 1rem;
            margin-bottom: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,.06); }
    .pill { background: #e8f5e9; color: #1b5e20; padding: .4rem .8rem;
            border-radius: 999px; display: inline-block; font-size: .85rem;
            margin-right: .35rem; }
    .pill.warn { background: #fff3e0; color: #bf360c; }
    ul { margin: .5rem 0 0; padding-left: 1.25rem; }
    a { color: #ff6b00; text-decoration: none; font-weight: 500; }
  </style>
</head>
<body>
  <h1>Attendance logged</h1>
  <div class="card">
    Week of <strong>{{ call_date }}</strong><br><br>
    <span class="pill">{{ attended|length }} attended</span>
    <span class="pill warn">{{ no_shows|length }} no-show{{ '' if no_shows|length == 1 else 's' }}</span>
  </div>

  <div class="card">
    <strong>Attendees</strong>
    <ul>
      {% for n in attended %}<li>{{ n }}</li>{% endfor %}
    </ul>
  </div>

  {% if no_shows %}
  <div class="card">
    <strong>No-shows (role-holders)</strong>
    <ul>
      {% for n in no_shows %}<li>{{ n }}</li>{% endfor %}
    </ul>
  </div>
  {% endif %}

  <p><a href="/">&larr; Log another</a></p>
</body>
</html>"""


@app.route("/", methods=["GET"])
def index():
    try:
        spreadsheet = connect_to_sheet()
        roster = read_roster(spreadsheet)
        tracker = spreadsheet.worksheet(TRACKER_TAB)
        _, current_row = find_current_call_row(tracker)
    except Exception as e:
        return f"<pre>Error loading sheet:\n{e}</pre>", 500

    call_date = current_row.get(COL_WEEK_OF, "?") if current_row else "?"
    role_holders = {}
    if current_row:
        role_holders = {
            "Shlok + Jaynaad": current_row.get(COL_SHLOK, ""),
            "Prasang": current_row.get(COL_PRASANG, ""),
            "Ending Shlok": current_row.get(COL_ENDING_SHLOK, ""),
            "Announcements": HARIBHAI_NAME,
        }

    return render_template_string(
        INDEX_HTML,
        roster=roster,
        role_holders=role_holders,
        call_date=call_date,
    )


@app.route("/submit", methods=["POST"])
def submit():
    passcode = request.form.get("passcode", "")
    if not ATTENDANCE_PASSCODE or passcode != ATTENDANCE_PASSCODE:
        return "<pre>Incorrect passcode.</pre>", 401

    attended = request.form.getlist("attended")
    if not attended:
        return "<pre>No attendees selected.</pre>", 400

    try:
        spreadsheet = connect_to_sheet()
        tracker = spreadsheet.worksheet(TRACKER_TAB)
        row_idx, current_row = find_current_call_row(tracker)
        if not row_idx or not current_row:
            return "<pre>Could not find current week's row in Tracker.</pre>", 404

        headers = tracker.row_values(1)
        call_date = current_row.get(COL_WEEK_OF, "")

        role_holders_map = {
            "Shlok + Jaynaad": current_row.get(COL_SHLOK, ""),
            "Prasang": current_row.get(COL_PRASANG, ""),
            "Ending Shlok": current_row.get(COL_ENDING_SHLOK, ""),
            "Announcements": HARIBHAI_NAME,
        }
        role_holders = [v for v in role_holders_map.values() if v]
        attended_set = set(attended)
        no_shows = [r for r in role_holders if r not in attended_set]
        no_shows_str = ", ".join(no_shows) if no_shows else "None"

        update_tracker_row(tracker, row_idx, headers, len(attended), no_shows_str)
        update_attendance_tab(spreadsheet, attended, call_date)

        if POST_TELEGRAM_CONFIRMATION:
            summary = generate_telegram_summary(
                call_date, attended, no_shows, role_holders_map
            )
            post_to_telegram(summary)

        return render_template_string(
            SUCCESS_HTML,
            attended=attended,
            no_shows=no_shows,
            call_date=call_date,
        )
    except Exception as e:
        return f"<pre>Error:\n{e}\n\n{traceback.format_exc()}</pre>", 500


@app.route("/healthz")
def healthz():
    return "ok", 200


if __name__ == "__main__":
    # Local dev only; Cloud Run uses gunicorn via the CMD override.
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 8080)), debug=False)
